// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAkOiZrzusjBaMwH20-zu6Q2-k31FMysk',
    appId: '1:931455965683:web:1af53d4f434a610aa59a86',
    messagingSenderId: '931455965683',
    projectId: 'vet-capstone-a4d8b',
    authDomain: 'vet-capstone-a4d8b.firebaseapp.com',
    storageBucket: 'vet-capstone-a4d8b.firebasestorage.app',
    measurementId: 'G-J012N97R31',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA29rPkiJkkFbzpp-2XypPeYsOzR0guX1o',
    appId: '1:931455965683:android:6eb8fa86c075dc45a59a86',
    messagingSenderId: '931455965683',
    projectId: 'vet-capstone-a4d8b',
    storageBucket: 'vet-capstone-a4d8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSgxA1wi0XhyqnF1kSf2oK6swZb8yWPu4',
    appId: '1:931455965683:ios:c97c6746ec25e32fa59a86',
    messagingSenderId: '931455965683',
    projectId: 'vet-capstone-a4d8b',
    storageBucket: 'vet-capstone-a4d8b.firebasestorage.app',
    iosBundleId: 'com.example.lebakanimalwellnessclinic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSgxA1wi0XhyqnF1kSf2oK6swZb8yWPu4',
    appId: '1:931455965683:ios:c97c6746ec25e32fa59a86',
    messagingSenderId: '931455965683',
    projectId: 'vet-capstone-a4d8b',
    storageBucket: 'vet-capstone-a4d8b.firebasestorage.app',
    iosBundleId: 'com.example.lebakanimalwellnessclinic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAkOiZrzusjBaMwH20-zu6Q2-k31FMysk',
    appId: '1:931455965683:web:8b69c36627e94da7a59a86',
    messagingSenderId: '931455965683',
    projectId: 'vet-capstone-a4d8b',
    authDomain: 'vet-capstone-a4d8b.firebaseapp.com',
    storageBucket: 'vet-capstone-a4d8b.firebasestorage.app',
    measurementId: 'G-YFK3KT15T2',
  );
}
